k8s_yaml('local-setup/k8s/mongo.yaml')
k8s_resource('mongo', port_forwards=27017, labels='databases')

k8s_yaml('local-setup/k8s/redis.yaml')
k8s_resource('redis', port_forwards=6379, labels='databases')


docker_build('example-server-image', '.')
k8s_yaml('local-setup/k8s/kubernetes.yaml')
k8s_resource('example-server', port_forwards=8000)