apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-server
  labels:
    app: example-server
spec:
  selector:
    matchLabels:
      app: example-server
  template:
    metadata:
      labels:
        app: example-server
    spec:
      containers:
        - name: example-server
          image: example-server-image
          ports:
            - containerPort: 8000